services:
  - type: web
    name: dare-demo-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_PHONE_NUMBER
        sync: false
      - key: BASE_URL
        sync: false
